// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwEMgXF7tNYuU-NPkYJ_MUcAQz0L1rJKo',
    appId: '1:471645046198:web:85fc30331f0d86f3e06d17',
    messagingSenderId: '471645046198',
    projectId: 'ecostaybd-eb86d',
    authDomain: 'ecostaybd-eb86d.firebaseapp.com',
    storageBucket: 'ecostaybd-eb86d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB30Wu-c7w1Hz6HhZch17hoE9T-ug6iFpY',
    appId: '1:471645046198:android:2ff63e007bbc31abe06d17',
    messagingSenderId: '471645046198',
    projectId: 'ecostaybd-eb86d',
    storageBucket: 'ecostaybd-eb86d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDAmPEOaPXQf9_Td-2EHPNmeQfpXb_UCw',
    appId: '1:471645046198:ios:a977413d9880e15de06d17',
    messagingSenderId: '471645046198',
    projectId: 'ecostaybd-eb86d',
    storageBucket: 'ecostaybd-eb86d.firebasestorage.app',
    iosClientId: '471645046198-a29lvf5hrm5pgamjjeebjspq3p9m7565.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecostay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDAmPEOaPXQf9_Td-2EHPNmeQfpXb_UCw',
    appId: '1:471645046198:ios:a977413d9880e15de06d17',
    messagingSenderId: '471645046198',
    projectId: 'ecostaybd-eb86d',
    storageBucket: 'ecostaybd-eb86d.firebasestorage.app',
    iosClientId: '471645046198-a29lvf5hrm5pgamjjeebjspq3p9m7565.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecostay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwEMgXF7tNYuU-NPkYJ_MUcAQz0L1rJKo',
    appId: '1:471645046198:web:94d8b9c41b34fbabe06d17',
    messagingSenderId: '471645046198',
    projectId: 'ecostaybd-eb86d',
    authDomain: 'ecostaybd-eb86d.firebaseapp.com',
    storageBucket: 'ecostaybd-eb86d.firebasestorage.app',
  );
}
