import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Frame8()])),
    );
  }
}

class Frame8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1612,
          height: 895,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1612,
                  height: 895,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1612,
                          height: 895,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 115,
                                top: 175,
                                child: Container(
                                  width: 246,
                                  height: 87,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 246,
                                          height: 87,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFF5F7F2),
                                            shape: RoundedRectangleBorder(
                                              borderRadius:
                                                  BorderRadius.circular(50),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 64,
                                        top: 27,
                                        child: SizedBox(
                                          width: 170,
                                          height: 30,
                                          child: Text(
                                            'Dashboard',
                                            style: TextStyle(
                                              color: const Color(0xFF216A44),
                                              fontSize: 24,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 17.81,
                                        top: 31,
                                        child: Container(
                                          width: 31.17,
                                          height: 26,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 26,
                                top: 3,
                                child: Container(
                                  width: 1586,
                                  height: 892,
                                  decoration: BoxDecoration(
                                    color: const Color(0xFFF5F7F2),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 26,
                                top: 3,
                                child: Container(
                                  width: 1586,
                                  height: 137,
                                  decoration: BoxDecoration(
                                    color: Colors.white,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1478,
                                top: 22,
                                child: Container(
                                  width: 100,
                                  height: 100,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF216A44),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1312,
                                top: 43,
                                child: SizedBox(
                                  width: 166,
                                  height: 29,
                                  child: Text(
                                    'María Gonzáles',
                                    style: TextStyle(
                                      color: Colors.black /* Grays-Black */,
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1312,
                                top: 72,
                                child: Text(
                                  'Viajero',
                                  style: TextStyle(
                                    color: const Color(
                                      0xFF8E8E93,
                                    ) /* Grays-Gray */,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.40,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 264,
                                top: 38,
                                child: Container(
                                  width: 1025,
                                  height: 79,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFF4F7F2),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(50),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 300,
                                top: 62,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(),
                                ),
                              ),
                              Positioned(
                                left: 343,
                                top: 55,
                                child: Text(
                                  'Buscar...',
                                  style: TextStyle(
                                    color: const Color(0xFF526F75),
                                    fontSize: 32,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.40,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 26,
                                top: 140,
                                child: Container(
                                  width: 1586,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(0xFFCFCFCF),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 81,
                                top: 3,
                                child: Container(
                                  width: 135,
                                  height: 137,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                        "https://placehold.co/135x137",
                                      ),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 743,
                        top: 308,
                        child: Container(
                          width: 721,
                          height: 452,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 721,
                                  height: 452,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(30),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 60,
                                top: 24.89,
                                child: Text(
                                  'Nombre',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF216A44),
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 65,
                                top: 100.55,
                                child: Text(
                                  'Correo',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF216A44),
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 57,
                                top: 176.22,
                                child: Text(
                                  'Teléfono',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF216A44),
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 64,
                                top: 247.90,
                                child: Text(
                                  'Cédula',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF216A44),
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 64,
                                top: 327.55,
                                child: Text(
                                  'Ciudad',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF216A44),
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 348,
                                top: 24.89,
                                child: Text(
                                  'María Gonzáles',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 358,
                                top: 251.88,
                                child: Text(
                                  'V-25.123.456',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 328,
                                top: 327.55,
                                child: Text(
                                  'Caracas, Venezuela',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 335,
                                top: 176.22,
                                child: Text(
                                  '+58 412 555 1234',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 285,
                                top: 100.55,
                                child: Text(
                                  'maria@correo.unimet.edu.ve',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 77.66,
                                child: Container(
                                  width: 721,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(0xFF8E8E93),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 153.32,
                                child: Container(
                                  width: 721,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(0xFF8E8E93),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 228.99,
                                child: Container(
                                  width: 721,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(0xFF8E8E93),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 304.65,
                                child: Container(
                                  width: 721,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(0xFF8E8E93),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 15,
                                top: 380.32,
                                child: Container(
                                  width: 191,
                                  height: 45.80,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF216A44),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(20),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 27,
                                top: 387.28,
                                child: Text(
                                  'Guardar Cambios',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 174,
                        top: 232,
                        child: Container(
                          width: 477,
                          height: 604,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 83.76,
                                child: Container(
                                  width: 477,
                                  height: 520.24,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 477,
                                          height: 420.66,
                                          decoration: ShapeDecoration(
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(
                                              borderRadius:
                                                  BorderRadius.circular(30),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 161.73,
                                        top: 25.10,
                                        child: Container(
                                          width: 152.51,
                                          height: 131.22,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFF216A44),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 58,
                                        top: 156.35,
                                        child: SizedBox(
                                          width: 354,
                                          height: 52.12,
                                          child: Text(
                                            'María Gonzáles',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors
                                                  .black /* Grays-Black */,
                                              fontSize: 40,
                                              fontFamily: 'Idiqlat',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 180.39,
                                        top: 206.49,
                                        child: Text(
                                          'Viajero',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF526F75),
                                            fontSize: 24,
                                            fontFamily: 'Jacques Francois',
                                            fontWeight: FontWeight.w400,
                                            height: 1.40,
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 21.50,
                                        top: 260.55,
                                        child: Container(
                                          width: 434.01,
                                          height: 50.21,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFF5F7F2),
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 1,
                                                color: const Color(
                                                  0xFFB3B3B3,
                                                ) /* Miscellaneous-Keyboards-Glyphs---Secondary */,
                                              ),
                                              borderRadius:
                                                  BorderRadius.circular(25),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 136.29,
                                        top: 270.08,
                                        child: SizedBox(
                                          width: 203.35,
                                          height: 31.16,
                                          child: Text(
                                            'Cambiar Foto',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors
                                                  .black /* Grays-Black */,
                                              fontSize: 24,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w500,
                                              height: 1.50,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: -2,
                                child: Text(
                                  'Mi Perfil',
                                  style: TextStyle(
                                    color: Colors.black /* Grays-Black */,
                                    fontSize: 40,
                                    fontFamily: 'Idiqlat',
                                    fontWeight: FontWeight.w400,
                                    height: 1.40,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 321,
                        top: 638,
                        child: SizedBox(
                          width: 184,
                          height: 44,
                          child: Text(
                            'Cerrar Sesión',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 24,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 397,
                        top: 140,
                        child: Container(
                          width: 218,
                          height: 80,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 56.72,
                                top: 24.83,
                                child: SizedBox(
                                  width: 150.65,
                                  height: 27.59,
                                  child: Text(
                                    'Explorar',
                                    style: TextStyle(
                                      color: const Color(0xFF216A44),
                                      fontSize: 36,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 15.78,
                                top: 28.51,
                                child: Container(
                                  width: 27.62,
                                  height: 23.91,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1022,
                        top: 140,
                        child: Container(
                          width: 246,
                          height: 80,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 64,
                                top: 24.83,
                                child: SizedBox(
                                  width: 170,
                                  height: 27.59,
                                  child: Text(
                                    'Perfil',
                                    style: TextStyle(
                                      color: const Color(0xFF216A44),
                                      fontSize: 36,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w800,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 17.81,
                                top: 28.51,
                                child: Container(
                                  width: 31.17,
                                  height: 23.91,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 704,
                        top: 140,
                        child: Container(
                          width: 229,
                          height: 80,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 59.58,
                                top: 24.83,
                                child: SizedBox(
                                  width: 158.25,
                                  height: 27.59,
                                  child: Text(
                                    'Reservas',
                                    style: TextStyle(
                                      color: const Color(0xFF216A44),
                                      fontSize: 36,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 16.58,
                                top: 28.51,
                                child: Container(
                                  width: 29.01,
                                  height: 23.91,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
