import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Frame7()])),
    );
  }
}

class Frame7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1586,
          height: 892,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1586,
                  height: 892,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1586,
                          height: 892,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 1586,
                                  height: 892,
                                  decoration: BoxDecoration(
                                    color: const Color(0xFFF5F7F2),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 1586,
                                  height: 137,
                                  decoration: BoxDecoration(
                                    color: Colors.white,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1452,
                                top: 19,
                                child: Container(
                                  width: 100,
                                  height: 100,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF216A44),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1286,
                                top: 40,
                                child: SizedBox(
                                  width: 166,
                                  height: 29,
                                  child: Text(
                                    'Miguel Angle',
                                    style: TextStyle(
                                      color: Colors.black /* Grays-Black */,
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1289,
                                top: 69,
                                child: Text(
                                  'Anfitrión',
                                  style: TextStyle(
                                    color: const Color(
                                      0xFF8E8E93,
                                    ) /* Grays-Gray */,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.40,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 322,
                                top: 35,
                                child: Container(
                                  width: 941,
                                  height: 79,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFF4F7F2),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(50),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 358,
                                top: 62,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(),
                                ),
                              ),
                              Positioned(
                                left: 401,
                                top: 55,
                                child: Text(
                                  'Buscar...',
                                  style: TextStyle(
                                    color: const Color(0xFF526F75),
                                    fontSize: 32,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.40,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 137,
                                child: Container(
                                  width: 1586,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(
                                          0xFF8E8E93,
                                        ) /* Grays-Gray */,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 92,
                                top: 0,
                                child: Container(
                                  width: 139,
                                  height: 137,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                        "https://placehold.co/139x137",
                                      ),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 171,
                                top: 137,
                                child: Container(
                                  width: 278,
                                  height: 87,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 72.33,
                                        top: 27,
                                        child: SizedBox(
                                          width: 192.11,
                                          height: 30,
                                          child: Text(
                                            'Dashboard',
                                            style: TextStyle(
                                              color: const Color(0xFF216A44),
                                              fontSize: 36,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 20.13,
                                        top: 31,
                                        child: Container(
                                          width: 35.22,
                                          height: 26,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 465,
                                top: 137,
                                child: Container(
                                  width: 350,
                                  height: 87,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 91.06,
                                        top: 27,
                                        child: SizedBox(
                                          width: 241.87,
                                          height: 30,
                                          child: Text(
                                            'Publicaciones',
                                            style: TextStyle(
                                              color: const Color(0xFF216A44),
                                              fontSize: 36,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 25.34,
                                        top: 31,
                                        child: Container(
                                          width: 44.34,
                                          height: 26,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1093,
                                top: 137,
                                child: Container(
                                  width: 170,
                                  height: 87,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 44.23,
                                        top: 27,
                                        child: SizedBox(
                                          width: 117.48,
                                          height: 30,
                                          child: Text(
                                            'Perfil',
                                            style: TextStyle(
                                              color: const Color(0xFFF5F7F2),
                                              fontSize: 36,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 12.31,
                                        top: 31,
                                        child: Container(
                                          width: 21.54,
                                          height: 26,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 831,
                                top: 137,
                                child: Container(
                                  width: 246,
                                  height: 87,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 64,
                                        top: 27,
                                        child: SizedBox(
                                          width: 170,
                                          height: 30,
                                          child: Text(
                                            'Reservas',
                                            style: TextStyle(
                                              color: const Color(0xFF216A44),
                                              fontSize: 36,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 17.81,
                                        top: 31,
                                        child: Container(
                                          width: 31.17,
                                          height: 26,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 194,
                        top: 256,
                        child: SizedBox(
                          width: 196,
                          height: 47,
                          child: Text(
                            'Mi Perfil',
                            style: TextStyle(
                              color: Colors.black /* Grays-Black */,
                              fontSize: 40,
                              fontFamily: 'Idiqlat',
                              fontWeight: FontWeight.w400,
                              height: 1.40,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 191,
                        top: 357,
                        child: Container(
                          width: 421,
                          height: 480,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 421,
                                  height: 415.60,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(30),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 142.74,
                                top: 23.16,
                                child: Container(
                                  width: 134.61,
                                  height: 121.07,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF216A44),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 30,
                                top: 144.26,
                                child: SizedBox(
                                  width: 354,
                                  height: 48.09,
                                  child: Text(
                                    'Miguel Angle',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black /* Grays-Black */,
                                      fontSize: 40,
                                      fontFamily: 'Idiqlat',
                                      fontWeight: FontWeight.w400,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 156.56,
                                top: 189.36,
                                child: Text(
                                  'Anfitrión',
                                  style: TextStyle(
                                    color: const Color(0xFF526F75),
                                    fontSize: 24,
                                    fontFamily: 'Jacques Francois',
                                    fontWeight: FontWeight.w400,
                                    height: 1.40,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 18.97,
                                top: 240.40,
                                child: Container(
                                  width: 383.06,
                                  height: 46.32,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFF5F7F2),
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        color: const Color(
                                          0xFFB3B3B3,
                                        ) /* Miscellaneous-Keyboards-Glyphs---Secondary */,
                                      ),
                                      borderRadius: BorderRadius.circular(25),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 120.29,
                                top: 249.18,
                                child: SizedBox(
                                  width: 179.47,
                                  height: 28.75,
                                  child: Text(
                                    'Carmbiar Foto',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Colors.black /* Grays-Black */,
                                      fontSize: 24,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w500,
                                      height: 1.50,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 676,
                        top: 290,
                        child: Container(
                          width: 721,
                          height: 559,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 721,
                                  height: 559,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(30),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 37,
                                top: 26,
                                child: Text(
                                  'Responsable',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF216A44),
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 65,
                                top: 102,
                                child: Text(
                                  'Correo',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF216A44),
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 57,
                                top: 178,
                                child: Text(
                                  'Teléfono',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF216A44),
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 85,
                                top: 250,
                                child: Text(
                                  'Rif',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF216A44),
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 34,
                                top: 406,
                                child: Text(
                                  'Cuenta PayPal',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF216A44),
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 23,
                                top: 330,
                                child: Text(
                                  'Dirección Fiscal',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF216A44),
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 360,
                                top: 26,
                                child: Text(
                                  'Miguel Angle',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 353,
                                top: 254,
                                child: Text(
                                  'J-12345678-9',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 282,
                                top: 330,
                                child: Text(
                                  'Calle Real, Mérida, Venezuela',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 298,
                                top: 406,
                                child: Text(
                                  'miguel.angle@paypal.com',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 334,
                                top: 178,
                                child: Text(
                                  '+58 414 555 7788',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 301,
                                top: 102,
                                child: Text(
                                  'miguelangle@correo.com',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 78,
                                child: Container(
                                  width: 721,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(0xFF8E8E93),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 154,
                                child: Container(
                                  width: 721,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(0xFF8E8E93),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 230,
                                child: Container(
                                  width: 721,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(0xFF8E8E93),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 306,
                                child: Container(
                                  width: 721,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(0xFF8E8E93),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 382,
                                child: Container(
                                  width: 721,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(0xFF8E8E93),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 458,
                                child: Container(
                                  width: 721,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(0xFF8E8E93),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 8,
                                top: 486,
                                child: Container(
                                  width: 191,
                                  height: 46,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF216A44),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(20),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 20,
                                top: 494,
                                child: Text(
                                  'Guardar Cambios',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w500,
                                    height: 1.50,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 309,
                        top: 682,
                        child: SizedBox(
                          width: 184,
                          height: 44,
                          child: Text(
                            'Cerrar Sesión',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 24,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1093,
                        top: 137,
                        child: Container(
                          width: 170,
                          height: 87,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 44.23,
                                top: 27,
                                child: SizedBox(
                                  width: 117.48,
                                  height: 30,
                                  child: Text(
                                    'Perfil',
                                    style: TextStyle(
                                      color: const Color(0xFF216A44),
                                      fontSize: 36,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w800,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 12.31,
                                top: 31,
                                child: Container(
                                  width: 21.54,
                                  height: 26,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
