import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Frame9()])),
    );
  }
}

class Frame9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1612,
          height: 895,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1612,
                  height: 895,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1586,
                          height: 892,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 1586,
                                  height: 892,
                                  decoration: BoxDecoration(
                                    color: const Color(0xFFF5F7F2),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 1586,
                                  height: 137,
                                  decoration: BoxDecoration(
                                    color: Colors.white,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1452,
                                top: 19,
                                child: Container(
                                  width: 100,
                                  height: 100,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF216A44),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1286,
                                top: 40,
                                child: SizedBox(
                                  width: 166,
                                  height: 29,
                                  child: Text(
                                    'Miguel Angle',
                                    style: TextStyle(
                                      color: Colors.black /* Grays-Black */,
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1289,
                                top: 69,
                                child: Text(
                                  'Anfitrión',
                                  style: TextStyle(
                                    color: const Color(
                                      0xFF8E8E93,
                                    ) /* Grays-Gray */,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.40,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 322,
                                top: 35,
                                child: Container(
                                  width: 941,
                                  height: 79,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFF4F7F2),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(50),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 358,
                                top: 62,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(),
                                ),
                              ),
                              Positioned(
                                left: 401,
                                top: 55,
                                child: Text(
                                  'Buscar...',
                                  style: TextStyle(
                                    color: const Color(0xFF526F75),
                                    fontSize: 32,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.40,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 137,
                                child: Container(
                                  width: 1586,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(
                                          0xFF8E8E93,
                                        ) /* Grays-Gray */,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 92,
                                top: 0,
                                child: Container(
                                  width: 139,
                                  height: 137,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                        "https://placehold.co/139x137",
                                      ),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 171,
                                top: 137,
                                child: Container(
                                  width: 278,
                                  height: 87,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 72.33,
                                        top: 27,
                                        child: SizedBox(
                                          width: 192.11,
                                          height: 30,
                                          child: Text(
                                            'Dashboard',
                                            style: TextStyle(
                                              color: const Color(0xFFF5F7F2),
                                              fontSize: 36,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 20.13,
                                        top: 31,
                                        child: Container(
                                          width: 35.22,
                                          height: 26,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 465,
                                top: 137,
                                child: Container(
                                  width: 350,
                                  height: 87,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 91.06,
                                        top: 27,
                                        child: SizedBox(
                                          width: 241.87,
                                          height: 30,
                                          child: Text(
                                            'Publicaciones',
                                            style: TextStyle(
                                              color: const Color(0xFF216A44),
                                              fontSize: 36,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 25.34,
                                        top: 31,
                                        child: Container(
                                          width: 44.34,
                                          height: 26,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1093,
                                top: 137,
                                child: Container(
                                  width: 170,
                                  height: 87,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 44.23,
                                        top: 27,
                                        child: SizedBox(
                                          width: 117.48,
                                          height: 30,
                                          child: Text(
                                            'Perfil',
                                            style: TextStyle(
                                              color: const Color(0xFF216A44),
                                              fontSize: 36,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 12.31,
                                        top: 31,
                                        child: Container(
                                          width: 21.54,
                                          height: 26,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 831,
                                top: 137,
                                child: Container(
                                  width: 246,
                                  height: 87,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 64,
                                        top: 27,
                                        child: SizedBox(
                                          width: 170,
                                          height: 30,
                                          child: Text(
                                            'Reservas',
                                            style: TextStyle(
                                              color: const Color(0xFF216A44),
                                              fontSize: 36,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 17.81,
                                        top: 31,
                                        child: Container(
                                          width: 31.17,
                                          height: 26,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1064,
                        top: 639,
                        child: Text.rich(TextSpan()),
                      ),
                      Positioned(
                        left: 1094,
                        top: 673,
                        child: Text.rich(TextSpan()),
                      ),
                      Positioned(
                        left: 1269,
                        top: 673,
                        child: Text.rich(TextSpan()),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 191,
                top: 166,
                child: Container(
                  width: 37,
                  height: 26,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 254,
                top: 166,
                child: SizedBox(
                  width: 241.87,
                  height: 30,
                  child: Text(
                    'Dashboard',
                    style: TextStyle(
                      color: const Color(0xFF216A44),
                      fontSize: 36,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 1.40,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
