import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Frame5()])),
    );
  }
}

class Frame5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1612,
          height: 895,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1612,
                  height: 895,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1612,
                          height: 895,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 115,
                                top: 175,
                                child: Container(
                                  width: 246,
                                  height: 87,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 246,
                                          height: 87,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFF5F7F2),
                                            shape: RoundedRectangleBorder(
                                              borderRadius:
                                                  BorderRadius.circular(50),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 64,
                                        top: 27,
                                        child: SizedBox(
                                          width: 170,
                                          height: 30,
                                          child: Text(
                                            'Dashboard',
                                            style: TextStyle(
                                              color: const Color(0xFF216A44),
                                              fontSize: 24,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 17.81,
                                        top: 31,
                                        child: Container(
                                          width: 31.17,
                                          height: 26,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 26,
                                top: 3,
                                child: Container(
                                  width: 1586,
                                  height: 892,
                                  decoration: BoxDecoration(
                                    color: const Color(0xFFF5F7F2),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 26,
                                top: 3,
                                child: Container(
                                  width: 1586,
                                  height: 137,
                                  decoration: BoxDecoration(
                                    color: Colors.white,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1478,
                                top: 22,
                                child: Container(
                                  width: 100,
                                  height: 100,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF216A44),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1312,
                                top: 43,
                                child: SizedBox(
                                  width: 166,
                                  height: 29,
                                  child: Text(
                                    'María Gonzáles',
                                    style: TextStyle(
                                      color: Colors.black /* Grays-Black */,
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1312,
                                top: 72,
                                child: Text(
                                  'Viajero',
                                  style: TextStyle(
                                    color: const Color(
                                      0xFF8E8E93,
                                    ) /* Grays-Gray */,
                                    fontSize: 20,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.40,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 264,
                                top: 38,
                                child: Container(
                                  width: 1025,
                                  height: 79,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFF4F7F2),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(50),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 300,
                                top: 62,
                                child: Container(
                                  width: 32,
                                  height: 32,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(),
                                ),
                              ),
                              Positioned(
                                left: 343,
                                top: 55,
                                child: Text(
                                  'Buscar...',
                                  style: TextStyle(
                                    color: const Color(0xFF526F75),
                                    fontSize: 32,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 1.40,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 26,
                                top: 140,
                                child: Container(
                                  width: 1586,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignCenter,
                                        color: const Color(0xFFCFCFCF),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 81,
                                top: 3,
                                child: Container(
                                  width: 135,
                                  height: 137,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                        "https://placehold.co/135x137",
                                      ),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 372,
                                top: 140,
                                child: Container(
                                  width: 218,
                                  height: 80,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 56.72,
                                        top: 24.83,
                                        child: SizedBox(
                                          width: 150.65,
                                          height: 27.59,
                                          child: Text(
                                            'Explorar',
                                            style: TextStyle(
                                              color: const Color(0xFF216A44),
                                              fontSize: 36,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 15.78,
                                        top: 28.51,
                                        child: Container(
                                          width: 27.62,
                                          height: 23.91,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1022,
                                top: 140,
                                child: Container(
                                  width: 179,
                                  height: 80,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 46.57,
                                        top: 24.83,
                                        child: SizedBox(
                                          width: 123.70,
                                          height: 27.59,
                                          child: Text(
                                            'Perfil',
                                            style: TextStyle(
                                              color: const Color(0xFF216A44),
                                              fontSize: 36,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 12.96,
                                        top: 28.51,
                                        child: Container(
                                          width: 22.68,
                                          height: 23.91,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 691,
                                top: 140,
                                child: Container(
                                  width: 229,
                                  height: 80,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 59.58,
                                        top: 24.83,
                                        child: SizedBox(
                                          width: 158.25,
                                          height: 27.59,
                                          child: Text(
                                            'Reservas',
                                            style: TextStyle(
                                              color: const Color(0xFF216A44),
                                              fontSize: 36,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 1.40,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 16.58,
                                        top: 28.51,
                                        child: Container(
                                          width: 29.01,
                                          height: 23.91,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 108,
                        top: 301,
                        child: Container(
                          width: 456,
                          height: 207,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 456,
                                  height: 207,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(50),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 35.36,
                                top: 23.75,
                                child: Container(
                                  width: 102.93,
                                  height: 67.02,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF216A44),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 35.36,
                                top: 103.50,
                                child: SizedBox(
                                  width: 291.40,
                                  height: 28,
                                  child: Text(
                                    '2',
                                    style: TextStyle(
                                      color: Colors.black /* Grays-Black */,
                                      fontSize: 48,
                                      fontFamily: 'Jaldi',
                                      fontWeight: FontWeight.w400,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 35.36,
                                top: 148.46,
                                child: SizedBox(
                                  width: 332.86,
                                  height: 28.84,
                                  child: Text(
                                    'Reservas Activas',
                                    style: TextStyle(
                                      color: const Color(0xFF526F75),
                                      fontSize: 20,
                                      fontFamily: 'Jacques Francois',
                                      fontWeight: FontWeight.w400,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 49.13,
                                top: 32,
                                child: Container(
                                  width: 76.87,
                                  height: 50.05,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 108,
                        top: 561,
                        child: Container(
                          width: 456,
                          height: 207,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 456,
                                  height: 207,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(50),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 35.36,
                                top: 23.75,
                                child: Container(
                                  width: 102.93,
                                  height: 67.02,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF216A44),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 35.36,
                                top: 103.50,
                                child: SizedBox(
                                  width: 291.40,
                                  height: 28,
                                  child: Text(
                                    '4',
                                    style: TextStyle(
                                      color: Colors.black /* Grays-Black */,
                                      fontSize: 48,
                                      fontFamily: 'Jaldi',
                                      fontWeight: FontWeight.w400,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 35.36,
                                top: 148.46,
                                child: SizedBox(
                                  width: 332.86,
                                  height: 28.84,
                                  child: Text(
                                    'Destinos Visitados',
                                    style: TextStyle(
                                      color: const Color(0xFF526F75),
                                      fontSize: 20,
                                      fontFamily: 'Jacques Francois',
                                      fontWeight: FontWeight.w400,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 49.13,
                                top: 32,
                                child: Container(
                                  width: 76.87,
                                  height: 50.05,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 108,
                        top: 226,
                        child: Text(
                          'Resumen de tu cuenta',
                          style: TextStyle(
                            color: Colors.black /* Grays-Black */,
                            fontSize: 40,
                            fontFamily: 'Idiqlat',
                            fontWeight: FontWeight.w400,
                            height: 1.40,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 681,
                        top: 378,
                        child: Container(
                          width: 810,
                          height: 365,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 810,
                                  height: 365,
                                  decoration: ShapeDecoration(
                                    color: Colors
                                        .white /* Backgrounds-(Grouped)-Secondary---Elevated */,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(50),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 292,
                                  height: 365,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage(
                                        "https://placehold.co/292x365",
                                      ),
                                      fit: BoxFit.cover,
                                    ),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.only(
                                        topLeft: Radius.circular(50),
                                        bottomLeft: Radius.circular(50),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 312,
                                top: 8,
                                child: SizedBox(
                                  width: 290,
                                  height: 49.03,
                                  child: Text(
                                    'Posada Los Frailes',
                                    style: TextStyle(
                                      color: Colors.black /* Grays-Black */,
                                      fontSize: 32,
                                      fontFamily: 'Idiqlat',
                                      fontWeight: FontWeight.w400,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 314,
                                top: 89,
                                child: SizedBox(
                                  width: 57,
                                  height: 32.69,
                                  child: Text(
                                    'Fecha',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: const Color(0xFF526F75),
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w300,
                                      height: 1.50,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 312,
                                top: 137,
                                child: SizedBox(
                                  width: 84,
                                  height: 32.69,
                                  child: Text(
                                    'Prestado',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: const Color(0xFF526F75),
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w300,
                                      height: 1.50,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 313,
                                top: 178,
                                child: SizedBox(
                                  width: 46,
                                  height: 32.69,
                                  child: Text(
                                    'Total',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: const Color(0xFF526F75),
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w300,
                                      height: 1.50,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 313,
                                top: 218,
                                child: SizedBox(
                                  width: 65,
                                  height: 32.69,
                                  child: Text(
                                    'Estado',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: const Color(0xFF526F75),
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w300,
                                      height: 1.50,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 631,
                                top: 96.97,
                                child: SizedBox(
                                  width: 154,
                                  height: 32.69,
                                  child: Text(
                                    '12-15 May 2026',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: const Color(0xFF38565C),
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w500,
                                      height: 1.50,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 700,
                                top: 137.28,
                                child: SizedBox(
                                  width: 85,
                                  height: 32.69,
                                  child: Text(
                                    'Carlos M',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: const Color(0xFF38565C),
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w500,
                                      height: 1.50,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 743,
                                top: 177.60,
                                child: SizedBox(
                                  width: 39,
                                  height: 32.69,
                                  child: Text(
                                    '84\$',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: const Color(0xFF38565C),
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w500,
                                      height: 1.50,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 712,
                                top: 217.91,
                                child: SizedBox(
                                  width: 73,
                                  height: 32.69,
                                  child: Text(
                                    'Pagado',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: const Color(0xFF38565C),
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w500,
                                      height: 1.50,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 313,
                                top: 48,
                                child: SizedBox(
                                  width: 67,
                                  height: 32.69,
                                  child: Text(
                                    'Merida',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: const Color(0xFF526F75),
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w500,
                                      height: 1.50,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 336,
                                top: 282,
                                child: Container(
                                  width: 423,
                                  height: 62.10,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF216A44),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(25),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 490,
                                top: 298,
                                child: SizedBox(
                                  width: 116,
                                  height: 30.51,
                                  child: Text(
                                    'Ver Detalles',
                                    style: TextStyle(
                                      color: Colors.white,
                                      fontSize: 20,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w500,
                                      height: 1.40,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 681,
                        top: 325,
                        child: Text(
                          'Proximo Viaje',
                          style: TextStyle(
                            color: const Color(0xFF526F75),
                            fontSize: 24,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w500,
                            height: 1.40,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
